version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.2
    container_name: keycloak
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
