version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:80"
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      - NGINX_HOST=incode.mx
      - NGINX_PORT=80
